# Stage 1: Build stage
FROM ubuntu AS builder

WORKDIR /app

COPY requirements.txt /app
COPY devops /app

RUN apt-get update && \
    apt-get install -y python3 python3-pip && \
    pip install --upgrade pip && \
    pip install -r requirements.txt

# Stage 2: Final stage
FROM python:3.9-slim

WORKDIR /app

#COPY --from=builder /usr/local/lib/python3.10/dist-packages /usr/local/lib/python3.10/dist-packages
COPY --from=builder /app /app
RUN pip install --no-cache-dir -r requirements.txt
ENTRYPOINT [ "python3" ]
CMD ["manage.py", "runserver", "0.0.0.0:8000"]
